apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot-app
  name: iot-app
  namespace: dev
spec:
  ports:
  - name: 8888-8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: iot-app
  type: ClusterIP
status:
  loadBalancer: {}

